### ISSUE TITLE
When multiple MIDI events have the exact same timestamp, only the first is delivered

### ISSUE THREAD

**Issue by brunchboy** [DerekCook/CoreMidi4J#1]
I just discovered that my Traktor Beat Phase sync is not working with CoreMIDI4J, and it did with MMJ. After a bunch of debugging, it appears that when Traktor sends a series of MIDI messages with the exact same timestamp, MIDI monitor sees all of them, but only the first gets to Java. For example, here:

23:10:10.486    From Traktor Virtual Output Control 1   Modulation Wheel (coarse)   72
23:10:10.486    From Traktor Virtual Output Control 1   Bank Select 1
23:10:10.486    From Traktor Virtual Output Control 1   Portamento Time (coarse)    101
23:10:10.562    From Traktor Virtual Output Control 1   Modulation Wheel (coarse)   82
23:10:10.603    From Traktor Virtual Output Control 1   Modulation Wheel (coarse)   95

In this sequence, only the Modulation Wheel messages are being delivered to me in the Java environment, because they are the first (or only) message to be sent with that particular timestamp. The fact that there is always a modulation wheel message before but with the same timestamp as the Bank Select 1 message, seems to prevent delivery of the Bank Select 1 message, which in turn blocks my beat phase mapping from being detected or working. (The Portamento Time message was an additional controller I added to the mapping while I was trying to diagnose the problem; it wasn’t until after I had added that, only to discover that I was not seeing that message either in Java, that I noticed the identical timestamps as a factor.)

When I subsequently turned off the sending of modulation wheel messages, I started seeing the Bank Select 1 messages getting through to Java, so it is definitely an issue of simultaneous timestamps being the issue rather than anything problematic about the messages themselves.

Please let me know if there is any other information that can help track down this issue!

**Comment by brunchboy** [comment]
My pull request seems to fix this issue. If you like the solution enough to merge, we can then close it.

**Comment by DerekCook** [comment]
Yes, figured out the issue with not scanning all packets in the MIDIPacket list so have already fixed that, but hadn't realised you could have multiple MIDI messages in the same packet! So will merge your contributions into the next build. Thanks for your suggestions and support.

**Comment by brunchboy** [comment]
Indeed, Apple seems to favor compactness over implementation simplicity, although I can’t really fault them for that. I wonder if we could pass along the timestamp information somehow as well? All the timestamps are showing as -1 in Java at the moment. I may investigate that a bit, though I don’t personally need them, if it is easy to preserve them that would appeal to my sense of completeness.

**Comment by DerekCook** [comment]
I don't need timestamps as well, so not a high priority for me. 

Your suggested code changes have been incorporated in the master branch, so I will close this issue.
