### ISSUE TITLE
TimeStamp don't working.

### ISSUE THREAD

**Issue by Pansmile** [DerekCook/CoreMidi4J#14]
TimeStamp seem to be not working now. But i remember that it used to work on previous master release.
I wrote a simple test class to represent this strange behavior. It uses the Snoize Midi-Monitor app to look for MIDI data. As i remember, this app can handle the timestamps.

```
import javax.sound.midi.*;
public class timeStampTest {
    public static void main(String[] args) throws MidiUnavailableException, InvalidMidiDataException, InterruptedException {
        MidiDevice.Info[] info = MidiSystem.getMidiDeviceInfo();
        MidiDevice device = null;

        //Getting the Midi-Monitor input from the system.
        for (MidiDevice.Info anInfo : info) {
            if (anInfo.getName().contains("Monitor") && anInfo.getName().contains("Core")) {
               device = MidiSystem.getMidiDevice(anInfo);
            }
        }
        //If Midi-Monitor is found, trying to send to it a couple of messages.
        if (device != null) {
            MidiMessage shortMessage = new ShortMessage(144, 60, 127);
            byte[] sysExData = new byte[]{(byte) 0xF0, (byte) 0x7f,(byte) 0x7f, (byte) 0x06, (byte) 0x02, (byte) 0xf7};
            MidiMessage sysExMessage = new SysexMessage(sysExData, sysExData.length);

            device.open();
            Receiver receiver = device.getReceiver();
            //Sending a short message with default timestamp.
            for (int i = 0; i < 5; i++) {
                receiver.send(shortMessage, -1);
                Thread.sleep(250);
            }
            //Just a spacer.
            receiver.send(new MetaMessage(1, sysExData, sysExData.length), -1);

            //Sending a SysEx message with default timeStamp.
            for (int i = 0; i < 5; i++) {
                receiver.send(sysExMessage, -1);
                Thread.sleep(250);
            }

            receiver.send(new MetaMessage(1, sysExData, sysExData.length), -1);

            //Sending a short message with non default timestamp.
            for (int i = 0; i < 5; i++) {
                receiver.send(shortMessage, 400000);
                Thread.sleep(250);
            }

            receiver.send(new MetaMessage(1, sysExData, sysExData.length), -1);

            //Sending a SysEx message with default timeStamp.
            for (int i = 0; i < 5; i++) {
                receiver.send(new SysexMessage(sysExData, sysExData.length), 500000);
                Thread.sleep(250);
            }
        }
    }
}
```

and MIDI monitor showed to me this:
![2016-03-20 19 14 58](https://cloud.githubusercontent.com/assets/17011774/13905425/7ccaa848-eed8-11e5-853c-29473d3848b3.png)

Can anyone repeat this?

UPD. Just tried the previous release and got the same behavior. Very strange. everything was ok just a couple of days before.

**Comment by DerekCook** [comment]
Might be worth James checking this with his test programs (and I am about to hit the road on business for a few days).

I've had a quick check of the 0.5 code to ensure that I have not inadvertently missed out the timestamp code which James worked on, and on a quick check it appears to present and correct in 0.5.

**Comment by Pansmile** [comment]
@DerekCook 
Hm. It seems to be more complex than i expected. Time stamping seems to work but.. partially.
I succeed in making timestamp work only one time per one lifecycle of the program. First time sending a message the timeStamp works but other times - not.

**Comment by Pansmile** [comment]
Well, it seems to be working. My test was incorrect. 
Or not.
UPD. As i understood, timestamp works only for the first time i send the message.
UPD. Yep. Timestamp works only if device was just opened. any other time it does not work.

**Comment by DerekCook** [comment]
Thinking about it (just stopped for a coffee whilst en-route!), have you allowed enough time for the offsets? 

The timestamp reference is relative to the number of **microseconds** since the port was opened. In the first case of the timed send (as opposed to -1 "don't care"), you're asking to wait for 400,000 microseconds or only 0.4S. So is that long enough? 

I ask, as your loops are timed in **milliseconds**. At a quick look you have six sleeps of 250ms (0.25S) so 1.5 seconds repeated twice or 3 seconds total before you get to the timed requests. So your request to wait 0.4S and 0.5S is in the past when you try and time the send of the messages . What if you wait for 4,000,000 (4S) and 5,000,000 (5S) respectively?

Also should the logic of your timed sends be incrementing the time offset. E.g 4000000, 4000000 + 250000, 4000000 + 500000, etc. 

As it is, the latter two loops are each requesting that the six messages they generate are all to be sent at the same time (which if the above is correct is already in the past, which probably has the same effect of -1 at that point)

**Comment by Pansmile** [comment]
I've noticed that and made other tests, tried to increase the timeStamps.  After all I get back to my app and  prooved my conclusion about opening device. 
Little bit later I'll maybe make simple swing app that sends a MIDI message by pushing a button with a timeStamp spinner. Just to illustrate the issue.

**Comment by Pansmile** [comment]
Well, i'm done with the swing test app.

```
import javax.sound.midi.*;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class PushTheButton extends JFrame {
    private JList<MidiDevice> destinations = new JList<>();
    private JTextField canReadTimeStamps = new JTextField();
    private JButton sendMessage = new JButton("Send");
    private JCheckBox openDeviceEachTime = new JCheckBox("Open device each time sending a message");
    private SysexMessage message;
    private JSpinner timeStampSpinner = new JSpinner(new SpinnerNumberModel(-1.0, -1.0, 10000.0,1.0));
    private MidiDevice selectedDestination;

    public PushTheButton() {
        super("TimeStamp Test");
        this.setBounds(200, 200, 200, 200);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container container = this.getContentPane();
        container.setLayout(new GridLayout(5, 1, 2, 2));
        container.add(destinations);
        container.add(canReadTimeStamps);
        container.add(openDeviceEachTime);
        container.add(sendMessage);
        container.add(timeStampSpinner);

        openDeviceEachTime.setSelected(false);

        //A cell renderer for the list of destinations.
        destinations.setCellRenderer((list, value, index, isSelected, cellHasFocus) -> {
            JLabel label = new JLabel(value.getDeviceInfo().getName() + " " + value.getDeviceInfo().getDescription());
            if (isSelected) {
                label.setBackground(Color.WHITE);
                label.setForeground(Color.BLUE);
            } else {
                label.setBackground(Color.WHITE);
                label.setForeground(Color.BLACK);
            }
            return label;
        });
        //Setting selection mode.
        destinations.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Destinations will be here.
        ArrayList<MidiDevice> destinationList = new ArrayList<>();
        MidiDevice.Info[] devicesInfo = MidiSystem.getMidiDeviceInfo();
        for (MidiDevice.Info anInfo : devicesInfo) {
            try {
                MidiDevice device = MidiSystem.getMidiDevice(anInfo);
                if (device.getMaxTransmitters() == 0) {
                    destinationList.add(device);
                }
            } catch (MidiUnavailableException e) {
                e.printStackTrace();
            }
        }
        //An array to share with destinations JList.
        MidiDevice[] destArray = new MidiDevice[destinationList.size()];
        int i = 0;
        for (MidiDevice aDest : destinationList) {
            destArray[i] = aDest;
            i++;
        }
        //Populating the JList with data.
        destinations.setListData(destArray);
        destinations.setMinimumSize(new Dimension(400, 200));
        canReadTimeStamps.setForeground(Color.BLACK);
        canReadTimeStamps.setEditable(false);

        //Selecting a destination where we will sending a message
        destinations.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                selectedDestination = destinations.getSelectedValue();
                //Checking if this destination supports timeStamps.
                if (selectedDestination.getMicrosecondPosition() > 0) {
                    canReadTimeStamps.setText("This device can read timeStamps");
                } else {
                    canReadTimeStamps.setText("This device can't read timeStamps");
                }
            }
        });

        //Creating a message to send;
        byte[] data = new byte[] {(byte) 0xF0, (byte) 0x7f,(byte) 0x7f, (byte) 0x02, (byte) 0x7f,  (byte) 0x01, (byte) 0xf7};
        try {
            message = new SysexMessage(data, data.length);
        } catch (InvalidMidiDataException e) {
            e.printStackTrace();
        }

        //Sending a message to selected destinations. Two modes of sending are available:
        //with opening the destination again each time or without opening it in case it is already open.
        sendMessage.addActionListener(e -> {
            long timeStamp = -1;
            double spinnerValue = (double) timeStampSpinner.getValue();
            if (spinnerValue > 0) {
                timeStamp = (long) spinnerValue * 1000;
            }
            try {
                if (openDeviceEachTime.isSelected() || !selectedDestination.isOpen()) {
                    selectedDestination.open();
                }
                Receiver receiver = selectedDestination.getReceiver();
                receiver.send(message, timeStamp);
            } catch (MidiUnavailableException e1) {
                e1.printStackTrace();
            }

        });
        setMinimumSize(new Dimension(500,500));
        pack();
        setVisible(true);

    }

    public static void main(String[] args) {
        PushTheButton test = new PushTheButton();
    }
}
```

and here is the executable jar:
https://drive.google.com/file/d/0B6YYf6GXg-xdcTgxZkZicXAtQmc/view?usp=sharing

On my system with the last CoreMidi4J release installed i have such a behavior:
When pushing the "sendMessage  button, if timestamp is -1 or 0 (visible in JSpinner at the bottom. Note, that the spinner works in milliseconds, not microseconds), everything works as expected. after incrementing it to f.e. 3000ms, nothing changes in behavior of the app. If than change  selection in list of destinations, first message will be sent with proper timeStamp and will appear only after 3 seconds. But if push the button again, message will appear instantly.
After selecting "Open device each time sending a message" checkBox, the behavior of the app returns to normal and timeStamp is always working.

**Comment by brunchboy** [comment]
I’m afraid I’m quite ill today (and hope to return to work tomorrow) so I don’t know when I will have time to experiment with this, but thank you for  it, and one of these days I will see if I can understand what is happening.

You are trying to combine timestamps with SysEx messages? Interesting, what do they do? I have not tried that.

Another thing which is different about your code than the way I have used MIDI from Java is that you are checking the `isOpen()` method. I never do that. I just open all devices as soon as they are detected, and keep them open as long as my application runs.

**Comment by Pansmile** [comment]
That's sad. Hope you'll get better soon.
I'm using SysEx message because of QLab, which is using MIDI Show Control for remote by default. But I tried to send short messages as well, it seems like it does' to matter which type of message I'm sending.
About opening the device: I have maybe a bad habit to do something with resources only when I'm sure that I really need them. Maybe that's the point, but I don't think this will change something. But I'l try.

**Comment by Pansmile** [comment]
I changed some moments in my test app.

```
import javax.sound.midi.*;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class PushTheButton extends JFrame {
    private JList<MidiDevice> destinations = new JList<>();
    private JTextField canReadTimeStamps = new JTextField();
    private JButton sendMessage = new JButton("Send");
    private JCheckBox openDeviceEachTime = new JCheckBox("Open device each time sending a message");
    private JCheckBox sendSysEx = new JCheckBox("Send a SysEx");
    private SysexMessage sysExMessage;
    private ShortMessage shortMessage;
    private JSpinner timeStampSpinner = new JSpinner(new SpinnerNumberModel(-1.0, -1.0, 10000.0,1.0));
    private MidiDevice selectedDestination;

    public PushTheButton() {
        super("TimeStamp Test");
        this.setBounds(200, 200, 200, 200);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container container = this.getContentPane();
        container.setLayout(new GridLayout(6, 1, 2, 2));
        container.add(destinations);
        container.add(canReadTimeStamps);
        container.add(openDeviceEachTime);
        container.add(sendSysEx);
        container.add(sendMessage);
        container.add(timeStampSpinner);

        openDeviceEachTime.setSelected(false);

        //A cell renderer for the list of destinations.
        destinations.setCellRenderer((list, value, index, isSelected, cellHasFocus) -> {
            JLabel label = new JLabel(value.getDeviceInfo().getName() + " " + value.getDeviceInfo().getDescription());
            if (isSelected) {
                label.setBackground(Color.WHITE);
                label.setForeground(Color.BLUE);
            } else {
                label.setBackground(Color.WHITE);
                label.setForeground(Color.BLACK);
            }
            return label;
        });
        //Setting selection mode.
        destinations.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Destinations will be here.
        ArrayList<MidiDevice> destinationList = new ArrayList<>();
        MidiDevice.Info[] devicesInfo = MidiSystem.getMidiDeviceInfo();
        for (MidiDevice.Info anInfo : devicesInfo) {
            try {
                MidiDevice device = MidiSystem.getMidiDevice(anInfo);
                if (device.getMaxTransmitters() == 0) {
                    device.open();
                    destinationList.add(device);
                }
            } catch (MidiUnavailableException e) {
                e.printStackTrace();
            }
        }
        //An array to share with destinations JList.
        MidiDevice[] destArray = new MidiDevice[destinationList.size()];
        int i = 0;
        for (MidiDevice aDest : destinationList) {
            destArray[i] = aDest;
            i++;
        }
        //Populating the JList with data.
        destinations.setListData(destArray);
        destinations.setMinimumSize(new Dimension(400, 200));
        canReadTimeStamps.setForeground(Color.BLACK);
        canReadTimeStamps.setEditable(false);

        //Selecting a destination where we will sending a message
        destinations.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                selectedDestination = destinations.getSelectedValue();
                //Checking if this destination supports timeStamps.
                if (selectedDestination.getDeviceInfo().getName().contains("Core")) {
                    canReadTimeStamps.setText("This device can read timeStamps");
                } else {
                    canReadTimeStamps.setText("This device can't read timeStamps");
                }
            }
        });

        //Creating a message to send;
        byte[] data = new byte[] {(byte) 0xF0, (byte) 0x7f,(byte) 0x7f, (byte) 0x02, (byte) 0x7f,  (byte) 0x01, (byte) 0xf7};
        try {
            sysExMessage = new SysexMessage(data, data.length);
            shortMessage = new ShortMessage(ShortMessage.NOTE_ON, 60 , 127);
        } catch (InvalidMidiDataException e) {
            e.printStackTrace();
        }

        //Sending a message to selected destinations. Two modes of sending are available:
        //with opening the destination again each time or without opening it in case it is already open.
        sendMessage.addActionListener(e -> {
            if (sendSysEx.isSelected()) {
                send(sysExMessage);
            } else {
                send(shortMessage);
            }

        });
        setMinimumSize(new Dimension(500,500));
        pack();
        setVisible(true);

    }

    private void send(MidiMessage message) {
        long timeStamp = -1;
        double spinnerValue = (double) timeStampSpinner.getValue();
        if (spinnerValue > 0) {
            timeStamp = (long) spinnerValue * 1000;
        }
        try {
            if (openDeviceEachTime.isSelected()) {
                selectedDestination.open();
            }
            Receiver receiver = selectedDestination.getReceiver();
            receiver.send(message, -1);
            Receiver receiver1 = selectedDestination.getReceiver();
            receiver1.send(message, timeStamp);
        } catch (MidiUnavailableException e1) {
            e1.printStackTrace();
        }
    }

    public static void main(String[] args) {
        PushTheButton test = new PushTheButton();
    }
}
```

and here is the jar:
https://drive.google.com/file/d/0B6YYf6GXg-xddjlCaG5ORG1WYUE/view?usp=sharing

Now you can select the type of message. By default it is a Note_On C3 with velocity 127. Selecting the sendSysEx checkbox will cause the sending of SysEx message (MIDI Show Control GO).
Also, now pushing the sendButton will cause sending of two identical messages, one with default timestamp and another with timestamp decoded from timeStamp JSpinner.

Also i've noticed that if opening the device when adding it to the list of destinations, even not CoreMidid4J devices don't return -1 or 0 at devise.getMicrosecondPosition. According to the MIDI SPI documentation that means device's possibility of working with timestamps. If device is closed it returns -1 for regular devices implementations and something else for CoreMidi4J implementations.

**Comment by brunchboy** [comment]
It is a fine practice to only use things when you know you need them! In the case of my light show software, I potentially need all of them, because I watch for MIDI clock messages coming from any device, and take notes about their characteristics.

I think the standard Java MIDI SPI is broken on the Mac when it comes to timestamp support, so we should not try to emulate it.

In any case, looking at the CoreMIDI4J source code, you definitely need to call `open()` in order for `getMicrosecondPosition()` to return reasonable results for you. We set our `startTime` instance variable when `open()` is called, and return the delta between that time and the current time when you call `getMicrosecondPosition()`. This is in accordance with the Java MIDI [spec](https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/MidiDevice.html#getMicrosecondPosition%28%29) which states:

> Obtains the current time-stamp of the device, in microseconds. If a device supports time-stamps, it should start counting at 0 when the device is opened and continue incrementing its time-stamp in microseconds until the device is closed. If it does not support time-stamps, it should always return -1.

Given that, you should consider the results of calling `getMicrosecondPosition()` on a device where you have not called `open()` to be undefined. But as long as you have opened it once, it will be fine.

Looking again at your source code, I believe I have come to understand your issue. I think you misunderstood the nature of the timestamp. It is an absolute timestamp, not a relative time. In other words, the value `1000` does not mean “1000 microseconds from now”, it means “at the time where `getMicrosecondPosition()` for the device would return the value `1000`, which is to say 1000 microseconds after the device was opened.

If you want to tell the device to send a message 1000 microseconds from now, the way you do that is by setting your timestamp to `getMicrosecondPosition() + 1000`.

And that is why things seemed to be working for you when you called `open()` again right before sending the message: that reset the device’s start time to be the current time, so the absolute timestamp acted as if it was a relative timestamp.

**Comment by brunchboy** [comment]
Oh, and thank you, I am _much_ better today, it was a 24-hour bug.

**Comment by Pansmile** [comment]
Thank you very much! Now i feel myself as a total idiot:).
The whole thing was about misunderstanding of the timeStamp nature.  Now I understand that in previous versions of my software I used to open the device each time I sent a message. That's why it worked. Than I changed it and my latency spinner stop working. 
Anyway, after that I decided to stop using time stamps and use a threads with TimeUnits.Microseconds.sleep() instead. That allows to delay messages even if destination does not support timestamps.
I think, I must close this issue now. Cause this was not a real issue but my stupidity:).

**Comment by DerekCook** [comment]
Don't be too hard on yourself. It took myself and James "quite a bit of debate" to reach a common understanding on how timestamps should be implemented. :-) 

Take a read of Issue https://github.com/DerekCook/CoreMidi4J/issues/6 for the gory detail of the debate it generated. 

The net result of our "passion" is that CoreMIDI4J might be the only MIDI implementation for Java that properly implements timestamps as per the Java Docs!

**Comment by brunchboy** [comment]
Please do not feel bad! The whole situation with timestamps in Java MIDI is _very_ confusing, and Derek and I spent at least a week talking back and forth and misunderstanding each other when we were trying to implement it.

Your approach of using `sleep()` is certainly viable and has the advantage that it does not require the MIDI device provider to support timestamps. The advantage of using timestamps with CoreMIDI is that they can help smooth jitter if you are sending MIDI messages over a network. CoreMIDI uses a MIDI RTP protocol which carries the timestamp information all the way across the network, and helps with coordination for distributed performances. If you are not doing that, you don’t need to worry about it.

**Comment by brunchboy** [comment]
Heh, @DerekCook, we were sending very similar messages at the same time. This does make me feel glad we took the time to sort it out back then though! :smile:

**Comment by Pansmile** [comment]
Thank you both for your help and wasting your time with me!
It's great to learn new things anyway.

**Comment by DerekCook** [comment]
No, it's all constructive if we come away with something, and it might have been a genuine problem. All debate is good if it furthers understanding, which is the lesson we learnt on Issue 6! :-)

**Comment by Pansmile** [comment]
By the way, is it possible to make a Java app to act as a mididevice in the system? I mean to have it's own ports visible to other midi invironment?
I found that this is barely possible, but what do you think?

**Comment by brunchboy** [comment]
By far the easiest way to have applications talk to each other over MIDI on the Mac is to use the Inter Application Commuinication (IAC) Bus that CoreMidi provides: https://sites.google.com/site/mfalab/mac-stuff/how-to-use-the-iac-driver

You could probably write an application that implemented and registered a MIDI device with the MIDISystem, though. I have simply never been interested in doing that, so I have not investigated what it would take.

**Comment by Pansmile** [comment]
IAC is great but this is not what I want:).
Anyway, it seems like midiSystem is the place were the Java's "write once" rule can't work anymore because of differences between core midi and Windows midi drivers.

**Comment by brunchboy** [comment]
Agreed, once you get down to a low enough level, you are leaving the magical dream world of Java. Good luck on this project! I just skimmed the Java MIDI API docs again, and I am not certain that what you want to do is possible from Java. But I would be interested to find I am wrong.

**Comment by Pansmile** [comment]
Yep, I didn't found any prooves that it's possible yet.
Thank you.

**Comment by Pansmile** [comment]
Maybe one of you knows is it possible to spy on MIDI destinations using Java?
I mean to catch a MIDI-message if it was sent from any source to selected destinations?
For now I can only catch messages which I am sending.

**Comment by brunchboy** [comment]
I am pretty certain there is no cross-platform way of doing that. The application MIDIMonitor for OS X does it, but it uses its own custom spying MIDI driver implemented in C++. It is open source, if that is of any help to you. The driver is here: https://github.com/krevis/MIDIApps/tree/master/Frameworks/SnoizeMIDISpy

The overall project is here: https://github.com/krevis/MIDIApps

**Comment by Pansmile** [comment]
Thank's
You answer is similar to one that I expected to get.
I use MIDIMonitor a lot and dream to partially implement it's functionality in my app cause using  external monitor every time is not very comfortable. 
Unfortunately, I don't know  jack in C++, that's why it's hard for me  to understand how this driver works.
Hope I'll learn C++ one day. But at first I need to learn Java:).

**Comment by DerekCook** [comment]
Maybe the studying the native code of CoreMidi4J will give you some pointers... :-)

**Comment by Pansmile** [comment]
I already got some:)
