### ISSUE TITLE
More graciously handle null attributes

### ISSUE THREAD

**Issue by brunchboy** [DerekCook/CoreMidi4J#15]
Currently, when creating a `CoreMidiDeviceProvider` instance, we use pretty harsh strings when we find that `deviceInfoDescription` or `deviceInfoManufacturer` are `null`, specifically: `"** Internal Error getting Device Description!"` and `"** Internal Error getting Device Manufacturer!"`

Having these be `null` seems to be a perfectly valid state, not an error condition. For example they are both `null` for the virtual MIDI output that Traktor creates to send clock data and other MIDI information on. The built-in midi SPI just copies the name to the description and uses `"Unknown vendor"` in that situation, I propose we do the same.

**Comment by Pansmile** [comment]
Hi,
I've got such situation just yesterday with virtual ports of a peace of software which name I can't remember today:).
I agree that copying the name to nullable description would be better, cause user don't actually need to see this "Internal error...".

**Comment by brunchboy** [comment]
OK, I have pushed source code changes that seem to make this work the way we want. It works on my system. But since I have to hack the Xcode project file to get it to build for me (`jni.h` is found in different places on our machines, and there is a hardcoded path to Derek's home directory), I would prefer to wait until @DerekCook has a chance to review this and include it in a future release.

**Comment by DerekCook** [comment]
I've just done a 0.6 release based on James' mods. If you're both happy with it, we can close this issue.

**Comment by brunchboy** [comment]
Thanks, Derek, that was much sooner than I expected, as this seemed like such a low priority issue. :grinning:  In any case, 0.6 seems great to me. I’m still working to wrap up Afterglow 0.2.1, which is going to be my most feature-packed release ever, but after that perhaps I will have some time to research how libusb manages their trick of embedding the native library within their single jar file.

**Comment by brunchboy** [comment]
By the way, I just wanted to thank you again for CoreMIDI4J. Thanks to its proper handling of SysEx messages, and ability to adjust to connection and disconnection of MIDI devices (and notify client software of such occurrences), my support for the Ableton Push and Novation Launchpad controller families is now completely automatic for users. They need only plug one of the supported devices in, and Afterglow detects it, identifies it, and activates an appropriate user interface on it. Turn it off or disconnect it, and everything is gracefully shut down. This is how things should work, and last year I thought it would never be possible.

**Comment by DerekCook** [comment]
No problem. Proper SYSEX support is of course what led me down the path of starting this project off as all the other SPIs had fallen by the wayside. Don't forget you have made important contributions as well. 

I'll close this issue now.We can always repoen it if needed.

**Comment by brunchboy** [comment]
I agree, closing seems appropriate. And I remember contributing here and there to this, certainly, but I would have never found the time to do all the tedious research and testing required to get the JNI relationships properly established with the Objective C side.
