### ISSUE TITLE
Crash in CoreMidi4J?

### ISSUE THREAD

**Issue by brunchboy** [DerekCook/CoreMidi4J#16]
This afternoon I was running a diagnostic tool to gather details about some buttons on my new Push 2 which have bounce issues, to submit to Ableton Support. At the same time I had a copy of Afterglow which was communicating with it via CoreMIDI4J, and it crashed with the attached log. I am submitting this in case it looks suspicious to Derek as well, or in case we see similar crashes in the future.
[hs_err_pid9021.log.txt](https://github.com/DerekCook/CoreMidi4J/files/200696/hs_err_pid9021.log.txt)

**Comment by Pansmile** [comment]
Unfortunately, I don't understand crash log files, but i also had some crashes. I attached logs which describe crashes in the same frame. I don't remember when and how I got this crashes.
Hope it would help somehow.
[hs_err_pid1757.log.txt](https://github.com/DerekCook/CoreMidi4J/files/201099/hs_err_pid1757.log.txt)
[hs_err_pid1782.log.txt](https://github.com/DerekCook/CoreMidi4J/files/201100/hs_err_pid1782.log.txt)
[hs_err_pid2439.log.txt](https://github.com/DerekCook/CoreMidi4J/files/201101/hs_err_pid2439.log.txt)
[hs_err_pid1417.log.txt](https://github.com/DerekCook/CoreMidi4J/files/201113/hs_err_pid1417.log.txt)

**Comment by brunchboy** [comment]
I don’t really know how to read JVM crash logs either, but I did see something suspicious that seems to occur in all of those crashes:

`Event: 1463.562 Thread 0x00007ff20e420800 Exception <a 'java/lang/NoClassDefFoundError': com/coremidi4j/CoreMidiException> (0x0000000770471a20) thrown at [/Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u72/5732/hotspot/src/share/vm/classfile/systemDictionary.cpp, line 199]`

And searching our source code reveals:

```
CoreMIDI4J/Native/CoreMidi4J/CoreMidi4JUtilities.cpp
42:  jclass Exception = env->FindClass("com/coremidi4j/CoreMidiException");
```

Indeed there is no such class; the closest we have is `uk.co.xfactorylibrarians.coremidi4j.CoreMidiException`. @DerekCook this looks like leftover code from before you settled on the package to use?

**Comment by brunchboy** [comment]
@Pansmile I wish we knew how to reproduce this. I am attaching a new build of the dynamic library where I have changed this line to look for the class as it now actually exists, and let’s see if we see it any more?
[libCoreMidi4J.dylib.zip](https://github.com/DerekCook/CoreMidi4J/files/201158/libCoreMidi4J.dylib.zip)

**Comment by brunchboy** [comment]
Well, after installing that new version of libCoreMidi4J.dylib, and trying various combinations of starting and stopping the diagnostic tool and Afterglow, I have been unable to reproduce the crash that led to me creating this issue. So, I have a slim hope this might fix it? But not full confidence. More time will tell, especially if you can remember, Oleg, and find a way to reproduce it with the old dylib but not this one.

**Comment by Pansmile** [comment]
I really can't remember how to reproduce those crashes. Maybe I'll try to reproduce your. Please, give me the link to the diagnostic tool you use. I'll try to install it and Afterglow and reproduce this crash.

**Comment by DerekCook** [comment]
Well spotted! The issue of the package name not being updated is of course not going to help, and I suspect it is the problem. Even if not we need to correct it. I'll also search the code to ensure there are no more instances of the old package name.

What we can do to see what the JVM does in this case is to adapt the code to do a test and deliberately throw the exception (with the incorrect package name) and see if we get a JVM crash.

I've got band practice today, but will look at this when I get back tonight.

**Comment by brunchboy** [comment]
Thanks, Oleg, but unfortunately the diagnostic tool is proprietary to Ableton, and I am not permitted to redistribute it. (I don’t think it would do anything if you do not have a Push 2 controller connected to your computer in any case.) I think Derek’s approach of intentionally trying to throw the nonexistent Exception class will be a good one.

**Comment by DerekCook** [comment]
I can confirm that if I deliberately call my exception handler as it currently is that I get the JNI crash. If I lookup the right class in the handler, then I don't get the crash. However the bad news is that Java does not see the exception, so I need to dig deeper on that.

**Comment by brunchboy** [comment]
Thanks for the update! Not crashing the VM is a _huge_ improvement. Having the exception delivered would be nice, too, of course, but not having my light shows freeze as the whole Java environment disappears is my biggest hope. :grin: I am running with a patched dynamic library, so there is no rush for another release while you investigate. I am in the process of pushing out the Afterglow 0.2.1 release, so I may have some time to research the embedding of the dynamic library this afternoon.

**Comment by brunchboy** [comment]
…although I guess the urgency depends on how many others are using the library, and whether Oleg wants to use the version I posted in this thread.

**Comment by brunchboy** [comment]
Another thing to consider: Your exception may be being thrown after all, but on a different thread than you think it is, where there is a catch block, or where it is silently terminating that thread?

**Comment by brunchboy** [comment]
Can we close this issue? I suspect it has been fixed.

**Comment by brunchboy** [comment]
Having not seen this for a year, I am closing this. If it turns up again, we can investigate further.

**Comment by DerekCook** [comment]
It's over a year old and to be honest, I am a little bit hazy on the issue now! I haven't seen any JVM crashes for a long time. 

Suggest we close the issue, and can always reopen or raise another one if required.

**Comment by DerekCook** [comment]
Ah, you beat me to it!

**Comment by brunchboy** [comment]
Great minds… 😉  Cheers! This was a lovely surprise for the weekend, thanks to @mpsalisbury!

**Comment by mpsalisbury** [comment]
Thanks for the quick pull!

**Comment by brunchboy** [comment]
You’re welcome! Thanks for helping kick me back into overdrive in my projects.
