### ISSUE TITLE
Cannot created midi in/out ports.

### ISSUE THREAD

**Issue by yamamo2shun1** [DerekCook/CoreMidi4J#25]
Hi,

I try to create the original midi in/out port and my code is as follows.
but I cannot create port.

Are there something wrong in my code?

My OS version is 10.13.4 and using JDK version is 1.8.0_172.

Thanks,

    import javax.sound.midi.MidiDevice;
    import javax.sound.midi.MidiSystem;
    
    import uk.co.xfactorylibrarians.coremidi4j.CoreMidiClient;
    import uk.co.xfactorylibrarians.coremidi4j.CoreMidiDeviceProvider;
    import uk.co.xfactorylibrarians.coremidi4j.CoreMidiException;
    import uk.co.xfactorylibrarians.coremidi4j.CoreMidiInputPort;
    import uk.co.xfactorylibrarians.coremidi4j.CoreMidiOutputPort;
    
    public class Main {
      public static void main(String[] args) {
    
        try {
          Class deviceProviderClass = Class.forName("uk.co.xfactorylibrarians.coremidi4j.CoreMidiDeviceProvider");
    
          if (CoreMidiDeviceProvider.isLibraryLoaded()) {
            System.out.println("create ...");
    
            CoreMidiClient midiClient = new CoreMidiClient("Test Client");
            CoreMidiInputPort midiInputPort = midiClient.inputPortCreate("Test In");
            CoreMidiOutputPort midiOutputPort = midiClient.outputPortCreate("Test Out");
    
            System.out.println("createed Test In/OUt Port.");
    
            for (MidiDevice.Info device : MidiSystem.getMidiDeviceInfo()) {
              System.out.println(device.getName() + " " + device.getDescription());
            }
          }
        } catch (ClassNotFoundException | CoreMidiException e) {
          e.printStackTrace();
        }
      }
    }

And the output is

    create ...
    createed Test In/OUt Port.
    Gervill Software MIDI Synthesizer
    Real Time Sequencer Software sequencer

**Comment by brunchboy** [comment]
Where did you get the idea that you should create a `CoreMidiClient` instance? That is something the Java runtime does, there is no need for your code to. Please use the example code in the README on the project page instead. That is all that you need to do. And in common cases, there is no need to interact with CoreMidi4J directly at all; as long as it is in your class path, Java will use it and make the fixed MIDI devices available through the normal Java MIDI interfaces.

What OS and Java version are you using?

**Comment by yamamo2shun1** [comment]
Sorry, I found the solution.

To create a virtual midi port, I need to call "MIDISourceCreate" instead of  "MIDIOutputPortCreate" in native code. 

Thanks,
