### ISSUE TITLE
"no receivers" error

### ISSUE THREAD

**Issue by bbulkow** [DerekCook/CoreMidi4J#26]
When I simply put  CoreMidi4J in my path and run, I get the following error:

Found APC40 - send sysex
MidiUnavailableException: sysex send CoreMidiSource has no receivers

I am running CoreMidi4J 1.1 download from your site, with the correct Jar.  I had trouble building, so I downloaded the jar and am running that way.

Any thoughts?

```
    MidiDevice.Info[] infos = MidiSystem.getMidiDeviceInfo();

    for (MidiDevice.Info info : MidiSystem.getMidiDeviceInfo()) {

    	System.out.println(" looking for the APC40 "+info.toString());

    	if (info.toString().contains("APC40")) {

    		System.out.println(" Found APC40 - send sysex");
    		try {
	    		SysexMessage sysMsg = new SysexMessage(  );
	    		sysMsg.setMessage(APC_MODE_SYSEX, APC_MODE_SYSEX.length);

	    		MidiDevice dev = MidiSystem.getMidiDevice(info);
	    		dev.open();
	    		Receiver r = dev.getReceiver();

	    		r.send(sysMsg, -1);
	    		sentSysEx = true;
	    		dev.open();
	    	}
	    	catch ( InvalidMidiDataException e ) {
				System.out.println("InvalidMidiDataException: sysex send " + e.getMessage());
	    	}
	    	catch ( MidiUnavailableException e ) {
				System.out.println("MidiUnavailableException: sysex send " + e.getMessage());
	    	}

        	break;
    	}
    	i++;
    }
```

**Comment by brunchboy** [comment]
I may be able to help debug this, but I am hoping @DerekCook will be able to weigh in as well: I don’t use the Java MIDI API from the Java language any longer, I use the much more expressive Clojure Lisp dialect in the JVM, and there I use Java MIDI indirectly through a Clojure wrapper provided by the Overtone project. So Derek will probably be more nimble in helping with this. 

That said, I can see one problem already. Your code is not checking to see that the MIDI device it is obtaining is the version that CoreMidi4J provides; it is only looking if the name contains `APC40`. It should also be making sure the name begins with `CoreMidi4J - `

I would encourage you to try compiling and running the example classes on the project main page, so you can verify that CoreMidi4J is loading properly, and so you can see the names under which your APC40 can be found both as a broken Java version and as a fixed CoreMidi4J version, and then update your code to make sure it is only trying to use the latter.

**Comment by brunchboy** [comment]
I think the other problem is that your code is not properly looking for the right instance of the device. I don’t know if this is true on other platforms, but on the Mac each MIDI device that is capable of bi-directional communication will show up twice, with the same name. One copy will be able to send MIDI to the device and that `MidiDevice` instance will return a non-zero value for `getMaxReceivers()`. But it will have zero transmitters, and be unable to receive MIDI from the device. The other copy will be the opposite. It will return a non-zero value for `getMaxTransmitters()` and will have zero receivers.

Your code is not checking those values before it is trying to call `getReceiver()`, and this is what is causing the exception you see, when it calls `getReceiver()` on the device whose name is APC40 but which would have returned zero if you had called `getMaxReceivers()` on it.

Note, however, that these are Java MIDI API issues, and not anything to do with CoreMidi4J.

**Comment by bbulkow** [comment]
Yes, knowing about the Mac midi engines that have no receivers, is exactly the problem.

Thanks.

There were no problems getting CoreMidi4J running, no problems selecting the "working" version, no need to search for "CoreMIDI4J".

Here is the output:

CoreMIDI4J Java classes are available.
Working MIDI Devices:
  CoreMIDI4J - Akai APC40
  CoreMIDI4J - Akai APC40
  Gervill
  Real Time Sequencer
CoreMIDI4J native library is running.
 looking for the APC40:: CoreMIDI4J - Akai APC40
 Found APC40 - send sysex
MidiUnavailableException: sysex send CoreMidiSource has no receivers
 looking for the APC40:: CoreMIDI4J - Akai APC40
 Found APC40 - send sysex
 looking for the APC40:: Gervill
 looking for the APC40:: Akai APC40
 looking for the APC40:: Akai APC40
 looking for the APC40:: Real Time Sequencer

In the interest of people looking for more comprehensive working examples, let me include this:

```

  public static class Example {

    public static boolean isCoreMidiLoaded() throws CoreMidiException {
      return CoreMidiDeviceProvider.isLibraryLoaded();
    }

    public static void watchForMidiChanges() throws CoreMidiException {
      CoreMidiDeviceProvider.addNotificationListener(new CoreMidiNotification() {
        public void midiSystemUpdated() {
          System.out.println("The MIDI environment has changed.");
        }
      });
    }

    public static MidiDevice.Info[] getWorkingDeviceInfo() {
      return CoreMidiDeviceProvider.getMidiDeviceInfo();
    }
  }

  void setAPC40Mode() {

  	boolean sentSysEx = false;
    int i = 0;


    //System.out.println(" APC40 2 Mode --- for non-mac ");
    MidiDevice.Info[] infos = MidiSystem.getMidiDeviceInfo();
    //System.out.println(" length of array is "+infos.length);

    try {
      Class deviceProviderClass = Class.forName(
        "uk.co.xfactorylibrarians.coremidi4j.CoreMidiDeviceProvider");
      System.out.println("CoreMIDI4J Java classes are available.");
      System.out.println("Working MIDI Devices:");
      for (javax.sound.midi.MidiDevice.Info device : Example.getWorkingDeviceInfo()) {
        System.out.println("  " + device);
      }
      if (Example.isCoreMidiLoaded()) {
        System.out.println("CoreMIDI4J native library is running.");
        //Example.watchForMidiChanges();
        //System.out.println("Watching for MIDI environment changes for thirty seconds.");
        //Thread.sleep(30000);
      } else {
        System.out.println("CoreMIDI4J native library is not available.");
      }
    } catch (Exception e) {
      System.out.println("CoreMIDI4J Java classes are not available.");
    }

    for (MidiDevice.Info info : MidiSystem.getMidiDeviceInfo()) {

    	System.out.println(" looking for the APC40:: "+info.toString());

    	if (info.toString().contains("APC40") && info.toString().contains("CoreMIDI4J")) {

    		System.out.println(" Found APC40 - send sysex");
    		try {
	    		SysexMessage sysMsg = new SysexMessage(  );
	    		sysMsg.setMessage(APC_MODE_SYSEX, APC_MODE_SYSEX.length);

	    		MidiDevice dev = MidiSystem.getMidiDevice(info);
	    		dev.open();
	    		Receiver r = dev.getReceiver();

	    		r.send(sysMsg, -1);
	    		sentSysEx = true;
	    		dev.open();
	    	}
	    	catch ( InvalidMidiDataException e ) {
				System.out.println("InvalidMidiDataException: sysex send " + e.getMessage());
	    	}
	    	catch ( MidiUnavailableException e ) {
				System.out.println("MidiUnavailableException: sysex send " + e.getMessage());
	    	}

        // try them all?
        //break;
    	}
    	i++;
    }
```

**Comment by brunchboy** [comment]
Excellent! I am glad to have been able to help get past that issue. Thanks so much for reporting back, and sharing your example.

**Comment by brunchboy** [comment]
Also, when you are ready to move on to a more production version of this code, if you are going to be always building and running with CoreMidi4J (and in Java 1.7 or later), I’d recommend following the advice in [Filtering Out Broken MIDI Devices](
https://github.com/DerekCook/CoreMidi4J#filtering-out-broken-midi-devices) and replacing your call to `MidiSystem.getMidiDeviceInfo()` with a call to our `CoreMidiDeviceProvider.getMidiDeviceInfo()`. That will save you the trouble of having to look for device names that begin with CoreMidi4J (and of remembering not to try doing that on non-Mac platforms); it will simply always just give you the best MIDI devices available on the platform that is running the code.

**Comment by DerekCook** [comment]
I am glad you have it working in principle, but I suggest that you follow James's suggestions, as you still seem to be using the standard MIDI functions for querying available devices.

Also, and there should be plenty of Java MIDI examples on this, you do not seem to be checking how many receivers and transmitters a returned device has. This would avoid the exceptions. 

If you haven't already done so, check out the [Oracle Java MIDI Tutorial ](https://docs.oracle.com/javase/tutorial/sound/overview-MIDI.html). I point you to standard Java MIDI here, as this is nothing to specific to CoreMIDI4J as we wrote it to be fully compatible with the Core Java MIDI APIs, the only exception to that rule be the `CoreMidiDeviceProvider.getMidiDeviceInfo()` to filter out broken devices or being able to register a notification listener for when the MIDI environment changes.

Going back to my comment about not checking for device capabilities, in this [Transmitting and Receiving MIDI Messages](https://docs.oracle.com/javase/tutorial/sound/MIDI-messages.html) page of the Java MIDI Tutorial provides guidance on how to use the standard API, including this advice

> To learn how many transmitters and receivers a device supports, you can use the following MidiDevice method:
> 
>   ` int getMaxTransmitters()`
>   ` int getMaxReceivers()`

Use these methods when iterating for the device you are looking for, to filter out a device that has no receivers when you want to send a message to the device and a device that has no transmitters when you want to receive a message. As James has mentioned, you will get to multiple `MidiDeviceInfo` objects for each physical device depending on its capabilities.

**Comment by bbulkow** [comment]
Hey. Thanks again for an awesome library.

The reason I'm not using CoreMidiDeviceProvider is I need the code to run on Windows and Linux as well, and I see no statement in your doc that class will work on those systems. Either I need to run conditionally on OS, or I need a statement from you about exactly what the expectation is on other systems. I expect you to be friendlier to MMJ and not simply crash, but I also don't expect you to have devices.

Perhaps I could code to look for CoreMidi, and if it's loaded but I don't find any devices fall back to the standard calls. That's a section of your documentation that could be improved.

Yes, it seems that another aspect is this get receivers thing, and that Mac you need to check for that. Since I"m speculatively sending SysEx, I can spray to everything in this version - working and non-working - so I can write ugly code.

Thanks for the super fast support and a good working library. I do think some example code that runs would be useful to others, in the form of java files, but I know java runtimes are hard and something that pastes in is pretty good too - I do wish your first example pasted in, it doesn't.

Also amazing your responsiveness here! Wow!

**Comment by brunchboy** [comment]
Thanks again, it’s always great to hear from people using our work, it helps justify the time we took in putting it out there. And hearing about problems that people run into is even more useful, because it helps us make it better.

The examples do work pasted in, but only if you paste them into two separate files with proper names. We are already planning a way to clarify the main “read me” page, and will probably pull them into a separate folder as actual files, as you suggest.

You can absolutely use CoreMidi4J on any platform, and if you call `CoreMidiDeviceProvider.getMidiDeviceInfo()` it will always give you the correct information for the platform it is actually running on. On the Mac it will give you the list of devices that actually work there, filtering out broken native implementations where we offer fixed replacements. On other platforms it delegates to the standard `MidiSystem.getMidiDeviceInfo()` and returns the set of native devices available on that platform.

I don’t know how we can be more clear about that, though… in [Filtering Out Broken MIDI Devices](
https://github.com/DerekCook/CoreMidi4J#filtering-out-broken-midi-devices) we say explicitly “The CoreMidi4J version works on any platform. If you call it on anything but a Mac, it simply gives you the same result you would get from the standard method. On the Mac, it filters out any devices which have broken SysEx implementations, and returns the CoreMidi4J versions instead. So to give your users the best experience possible, simply embed CoreMidi4J, and use its implementation of getMidiDeviceInfo() wherever you would otherwise have used the standard one, and your users will always only see working MIDI devices.”

**Comment by brunchboy** [comment]
(And, as an aside, the reason our code example is split into two separate files is because one of the things it is trying to do is to show how to safely check for the presence of the CoreMidi4J library, which requires you to use ugly reflective Java code as in the `Available` class, but we wanted the `Example` class to show the more natural code you can write once you have confirmed that CoreMidi4J is on your class path. But that means that `Example` will not load otherwise, you will crash with a `NoClassDefFoundError`.)

**Comment by brunchboy** [comment]
And, actually, that gives me another idea of how to make the example easier to understand. I first created it _before_ it was safe to try to use CoreMidi4J on other platforms, so our recommendation was to write code that checked if it was present.

Later on we came up with the much more developer-friendly approach of putting all the necessary safety and platform checks in our own code before attempting to load our native libraries on the Mac, and even embedding those native libraries inside the CoreMidi4J jar itself. So the recommendation today is always to just bundle CoreMidi4J, which means that it’s no longer necessary to perform those reflective tests.

I think that it is past time for me to remove them, which will leave us with a single, simpler Java class as an example, which will make things much simpler to explain and understand even if people just want to cut and paste code. How does that grab the two of you?

**Comment by bbulkow** [comment]
Grabs me great! It's hard to estimate the difficulty of dealing with ageing MMJ on multiple platforms, your code is super spiffy - I bet a quick roll through your doc with the appropriate amount of protection for cross-platform authors would be greatly ( although silently :-) ) appreciated by many.

( I have a thing about this.... for example, 'ln -s', where the documentation's first paragraph is impossible to read. The example talks about SRC and TARGET and the paragraph talks about "original" and "link" so it's not conceivable to know the parameter ordering... there are lots of examples in documentation where such a small change can make such a big difference! In my product, I regularly run in-person user tests, it's cleared thing up immeasurably. )

**Comment by brunchboy** [comment]
Derek, even though you’ve been to busy to weigh in, I have gone ahead and followed this plan. As I noted in the commit message, I can’t think of a single other library whose code examples have complicated themselves in order to show how to cleanly work when you have not included the library on the class path. And getting rid of that has enabled me to make a single, focused example class that works on its own, and calls attention to the aspects people are actually trying to learn.

I have also reordered a bit, and removed a bunch of legacy text from the old days when we thought you might not have the library on some platforms. Things are now much less likely to cause this sort of confusion; please let me know if you see any issues when you have time.

**Comment by brunchboy** [comment]
I also just realized that our opening sentence was outdated and made it seem that this SPI could only be installed/used on the Mac. I have now fixed that as well; better to set the correct expectations from the beginning, instead of trying to correct them later in the document.

**Comment by DerekCook** [comment]
Just catching up now, James, and have skimmed the doc changes. They look good.

And just to confirm, my code is developed on Mac, tested on PC, and I do know some people who run on Linux, and CoreMIDI4J is in all of them, transparently on PC and Linux. That was one thing I wanted when developing it!
