### ISSUE TITLE
Java midi (not fixed by CoreMidi4J) incorrectly posting Start/Stop/Continue/Clock etc. as 0xF0

### ISSUE THREAD

**Issue by eclab** [DerekCook/CoreMidi4J#27]
It appears that for these messages (and I'm guessing all messages > 0xF0), Java midi is reporting 0xF0 in getCommand(), and CoreMidi4J does not fix it.

There appears to be an ugly workaround: getChannel() provides the remaining data as if the message was a channel command.    Thus Clock (0xF0) reports getCommand() = 0xF0 and getChannel() = 0x08.  Similarly, Start (0xFB) reports getCommand() = 0xF0 and getChannel() = 0x0B.  Yuck.

I have not Java's behavior on anything other than Macs with and without CoreMidi4J.  I believe I'm running the latest CoreMidi4J, Java SE 1.8.0_151-b12, OS X 10.13.2.

**Comment by brunchboy** [comment]
I’m not sure what you mean by this. I have been able to send start, stop, continue, and clock messages with no problems. Can you be more specific about what you are trying to do, perhaps showing sample code?

**Comment by brunchboy** [comment]
It seems you are simply misunderstanding the Java MIDI API. From the [Javadoc](https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/ShortMessage.html#getCommand()) for `ShortMessage.getCommand()`:

> This method assumes that the event is a MIDI channel message; if not, the return value will not be meaningful.

Don’t attempt to use `getCommand()` with non-channel messages like clock messages.

**Comment by brunchboy** [comment]
The entire purpose of `getCommand()` is to help you separate out the command and channel bits of MIDI channel messages, in which both are combined in the status byte. If you look at its source code, you can see exactly why you are getting the results you saw:

```java
    /**
     * Obtains the MIDI command associated with this event.  This method
     * assumes that the event is a MIDI channel message; if not, the return
     * value will not be meaningful.
     * @return the MIDI command associated with this event
     * @see #setMessage(int, int, int, int)
     */
    public int getCommand() {
        // this returns 0 if an invalid message is set
        return (getStatus() & 0xF0);
    }
```

In the case of a non-channel message like a clock message, the entire status byte is the value of the message, so you just want to call `getStatus()` to obtain it.

**Comment by eclab** [comment]
> It seems you are simply misunderstanding the Java MIDI API. From the [Javadoc](https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/ShortMessage.html#getCommand()) for `ShortMessage.getCommand()`:
> 
> > This method assumes that the event is a MIDI channel message; if not, the return value will not be meaningful.
> 
> Don’t attempt to use `getCommand()` with non-channel messages like clock messages.

Then I am a big dummy; and should be using getStatus().  Feel free to close out.

**Comment by brunchboy** [comment]
MIDI is really old, from when it was important to cram as much value out of every single bit as could possibly be used. And the Java MIDI API does not do a great job of shielding you from that. It’s confusing and tricky. I have been messed up on more than one occasion by it. Don’t feel bad! 😄
