### ISSUE TITLE
Midi Outpus not working on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by git-moss** [DerekCook/CoreMidi4J#32]
I am the author of DrivenByMoss which supports several controller devices for Bitwig and Reaper. The Reaper version uses CoreMidi4J to fix the Java macOS issues. Many thanks for that library!

I just noticed that all controllers do not receive MIDI anymore (MIDI in works fine). I activated now the default Java MIDI devices and with them it works as expected.

I use OpenJDK 11.0.3+7 from the AdoptOpenJdk site but since I use that version for quite some time I can only suspect it is related to the latest OS updates.
Since my macOS coding skills are pretty basic it would be great if you could look in that.

**Comment by DerekCook** [comment]
Hi, I'm afraid that this is probably something that I won't be able to investigate myself for the time being, as my Mac is 2011 vintage and Apple have blocked the update to Mojave for me as my computer is not man enough to run it. I will be buying a new Mac Christmas time.

I don't know what James is running on?

**Comment by DerekCook** [comment]
PS: If neither myself of James have Mojave ,then I guess the next step would be a debug build with tracing statements enabled, so we can try and see what is happening remotely.

It might also be worth you coming up with some sample test Java code that reproduces the issue that we can take a look at.

**Comment by brunchboy** [comment]
I am using Mojave 10.14.6, and my MIDI inputs and outputs work just fine. I tried with both my old Oracle JDK 1.8, and with OpenJDK 11.0.4 from Amazon (Corretto). Have you tried using the recently-released CoreMidi4J 1.2, which fixes an issue with MIDI device names under Java 11?

But I am afraid that if we can’t reproduce this, we are unlikely to be able to help figure out what is happening.

**Comment by git-moss** [comment]
Thanks for the quick feedback! I forgot to mention that I tried with both 1.1 and 1.2. Will try to dig deeper...

**Comment by brunchboy** [comment]
Best of luck, I hope we can track this down. As Derek mentioned, we may need to create a debugging build with more logging to see where things are falling apart if they can be definitively traced to CoreMidi4J. Oh, and I just realized I’d heard of your controller drivers before, as an artist who uses my Beat Link Trigger was working with them and looking for some configuration assistance with them and BitWig. 😄

**Comment by git-moss** [comment]
Strangely, it started to work again and I cannot reproduce the error anymore. The wonders of Macos :-) Will close it for the time being.
