### ISSUE TITLE
CoreMIDI4J not correctly naming EndPoints for an ESI-M8U

### ISSUE THREAD

**Issue by DerekCook** [DerekCook/CoreMidi4J#34]
As it says in the title.

This is a report from a user, Jeremy, which we are discussing via emails, who hopefully also has the solution, but I have logged this so we can start considering the issue, and I will invite Jeremy to start contributing to this issue.

<img width="247" alt="Bildschirmfoto 2019-11-15 um 23 05 01" src="https://user-images.githubusercontent.com/11217268/69005182-3d43b780-0916-11ea-9cd2-015b6132fdc3.png">

Jeremy refers to [Apple Technical QA1374](https://developer.apple.com/library/archive/qa/qa1374/_index.html) for sample code on how to name an end point, which I have never seen before. I recommend that we review this as part of addressing the fix.

As mentioned, Jeremy should also have a recommended fix, so we just need to look at reviewing, and merging the pull request, and testing across our devices.  

<img width="696" alt="Bildschirmfoto 2019-11-16 um 21 33 13" src="https://user-images.githubusercontent.com/11217268/69005210-9f042180-0916-11ea-9b7a-d1e65daa055c.png">

I'd like to look at doing this one, as I have had little time to support the previous fixes. I have a bit more time now, and would like to refresh my knowledge on how to build CoreMIDI4J! :)

**Comment by DerekCook** [comment]
Hi. Jeremy

Thanks. Will take a look at your suggestion, once I get the build ENV up and running again. 

CoreMIDI4J 1.2 is working correctly with my multi port device, so it must be something specific to the ESI-8MU and other interfaces reporting in a similar manner....

![motif_factory_Preferences_and_motif_factory_-_Yamaha_Motif_ES_Series_Librarian_and_YamahaMusicians_com_-_Index_page](https://user-images.githubusercontent.com/11217268/69008858-28334c80-0947-11ea-829b-86dc1e8ba4b7.png)

So, the test will be to get your suggested change incorporated and ensure that I still get the same result. 

Will keep you posted.

**Comment by DerekCook** [comment]
Hi,

Apart from one small change I had to make, Jeremy's code is incorporated and working in a 1.3-SNAPSHOT. 

[coremidi4j-1.3-SNAPSHOT.jar.zip](https://github.com/DerekCook/CoreMidi4J/files/3855800/coremidi4j-1.3-SNAPSHOT.jar.zip)

The issue I had is that with the code as it was, I was getting a name like "DEVICE DEVICE ENDPOINT" instead of "DEVICE ENDPOINT" on my multi port device

So I modified the code in `Java_uk_co_xfactorylibrarians_coremidi4j_CoreMidiDeviceProvider_getMidiDeviceInfo`

From 

`     
 if ( deviceName != NULL ) {

      CFStringAppend(buildName, (deviceName != NULL ) ? deviceName :  CFSTR("<Unknown Device>") );

      if ( numberOfEntities > 1 ) {

        CFStringAppend(buildName, CFSTR(" "));
        CFStringAppend(buildName, (endpointName != NULL ) ? endpointName :  CFSTR("<Unknown Endpoint>") );

      }

    } else {

      CFStringAppend(buildName, (endpointName != NULL ) ? endpointName :  CFSTR("<Unknown Device>") );

    }

`
to

`  
if ( buildName != NULL ) {

    if ( deviceName != NULL ) {

      if ( numberOfEntities > 1 ) {

        CFStringAppend(buildName, CFSTR(" "));
        CFStringAppend(buildName, (endpointName != NULL ) ? endpointName :  CFSTR("<Unknown Endpoint>") );

      } else {
        
        CFStringAppend(buildName, (deviceName != NULL ) ? deviceName :  CFSTR("<Unknown Device>") );
        
      }

    } else {

      CFStringAppend(buildName, (endpointName != NULL ) ? endpointName :  CFSTR("<Unknown Device>") );

    }`

I.e. I do not use the device name any more if there is more than one end point, as it is now provided by the modified code provided by Jeremy
Which seems to work for my single and multi end point devices

**Comment by DerekCook** [comment]
Thanks, Jeremy. 

I have incorporated this latest change, and all seems good.

[coremidi4j-1.3-SNAPSHOT.jar.zip](https://github.com/DerekCook/CoreMidi4J/files/3856023/coremidi4j-1.3-SNAPSHOT.jar.zip)

I've also just rebuilt dx.factory with the latest snapshot and reuploaded it for you.

**Comment by brunchboy** [comment]
This sounds promising! Let me know when you’d like a release published. Or, if you have created an account on the [OSSRH JIRA](https://issues.sonatype.org/), I can open a ticket for you to be able to publish them yourself, once you set up proper credential management on your build machine. The details are lost in the mists of time in my mind, but I am sure we could figure them out again.

**Comment by DerekCook** [comment]
Latest snapshot with Jeremy's pull request. All seems to be working with my librarians.

[coremidi4j-1.3-SNAPSHOT.jar.zip](https://github.com/DerekCook/CoreMidi4J/files/3871463/coremidi4j-1.3-SNAPSHOT.jar.zip)

**Comment by brunchboy** [comment]
Should I publish a release?

**Comment by DerekCook** [comment]
Hi, 

Yes if you can, it seems OK over here, and I have heard nothing against it

**Comment by brunchboy** [comment]
All right, 1.3 is released! Time to update my projects to refer to it… 😄

**Comment by DerekCook** [comment]
Thanks, James. :)
