### ISSUE TITLE
Support Macos on ARM

### ISSUE THREAD

**Issue by git-moss** [DerekCook/CoreMidi4J#40]
Would be great if you could release a version with a ARM support. As far as I could test it is sufficient to recompile it with the latest Xcode. The dylib then contains both versions.

And thanks for this great library!

**Comment by brunchboy** [comment]
It is built by GitHub Actions. If you could research whether they offer a recent enough version of Xcode, and submit a pull request with whatever changes are needed to the workflow (or simply confirm that you have tested your fork and that a simple rebuild solves the problem) that would be most welcome! Neither of us have Arm-based Macs on which to test ourselves.

**Comment by brunchboy** [comment]
From my own research, it may be some time before we will be able to offer this. GitHub says:

> Note: The macOS 11.0 virtual environment is currently provided as a private preview only. Any users or organizations that are already using this runner can continue using it, but we're not accepting any further users or organizations at this time. The macos-latest YAML workflow label still uses the macOS 10.15 virtual environment.

**Comment by brunchboy** [comment]
Ah,  but perhaps we are in luck. Even on the macOS 10.15 virtual environment, this is the version of Xcode:
> Xcode Command Line Tools 12.4.0.0.1.1610135815

That does appear to be current. So, @git-moss it would likely be worth your while to push a commit to a fork of this project, and see if the resulting build works on your Apple Silicon machine. We’d very much like to know that. If it does, then we will push out a new release which just results in a new compile with this latest Xcode tool chain.

**Comment by git-moss** [comment]
Thanks for the quick reply!

By coincidence I started looking into GitHub actions yesterday and read this macOS comment too but did not notice the updated command line tools info!

As expected a simple recompile adds now the arm version as well since this is the default. To trigger a recompile I increased the version number and being at it fixed the deprecated set-env.

I issued a Pull-Request for these changes.

**Comment by brunchboy** [comment]
That’s great, I apologize that the project was still using the deprecated approach for setting environment variables, if I had realized that I would have fixed it before asking you to do this. But you managed to sort it out! And I saw that your final workflow succeeded, so I was about to ask you if it built the library in the correct way. Thank you for the confirmation that it did, I will merge your PR, and as soon as we can get a little testing done, we should be able to make this a non-snapshot release.

**Comment by brunchboy** [comment]
(See #41 for the related PR.)

**Comment by git-moss** [comment]
Thank you!

**Comment by DerekCook** [comment]
Hi, 

I am a little late to the party as usual due to a manic work week, but James is always ably on the case. :-)

I've had a little time this morning to check out the 1.6 SNAPSHOT in one of my librarians this morning and this seems fine on OSX 11.2.1 on Intel.

**Comment by brunchboy** [comment]
As it happens I am suddenly and temporarily in possession of an Apple Silicon Mac: My day job rented one of the transition machines for some testing purposes by our ops team, and as the team agent, I’m responsible for shipping it back to Apple now that they are reminding us they will want it soon. So I was able to build a version of Beat Link Trigger with this snapshot of CoreMidi4J embedded, and test that it does indeed work properly both on Intel and Apple Silicon Macs. It’s probably time to promote this to an actual release.

**Comment by brunchboy** [comment]
(I also took this opportunity to update my Carabiner project, which is a loose bridge to Ableton Link, to build universal binaries that work on both Intel and Apple Silicon. That took a bit more work because I am using cmake to drive the build, across Macs and other platforms, so I had to adjust my build configuration to explicitly request this. But thanks again for getting this on my radar, @git-moss!)

**Comment by brunchboy** [comment]
OK, the release is done!

**Comment by git-moss** [comment]
Thanks! Glad I could help!

**Comment by DerekCook** [comment]
Cool. 👍
