### ISSUE TITLE
Running on the M1

### ISSUE THREAD

**Issue by eclab** [DerekCook/CoreMidi4J#42]
Any ETA on binaries compiled for the M1?  I am told that at present CoreMidi4J (and hence Edisyn) can only run under Rosetta.

**Comment by git-moss** [comment]
CoreMidi4J is already adapted to ARM Macos. See here: https://github.com/DerekCook/CoreMidi4J/issues/40

**Comment by eclab** [comment]
My apologies for the annoyance then!
