### ISSUE TITLE
isLibraryLoaded() returns true, but getMidiDeviceInfo() doesn't return any CoreMIDI4j devices

### ISSUE THREAD

**Issue by vlucenaBigSweetOwl** [DerekCook/CoreMidi4J#44]
I'm working on a project in Processing that uses the MidiBus library to send MIDI messages and play notes out loud. It works just fine on Windows with Microsoft GS Wavetable Synth but knowing I would have problems with Macs, I had someone with a Mac help me test if I could use CoreMIDI4j.

So on a Mac when I run the following 
`try{println(CoreMidiDeviceProvider.isLibraryLoaded());}catch(Exception e){}`
I get it printing true, but if I do
`println(CoreMidiDeviceProvider.getMidiDeviceInfo().length)`
It prints 2 because the only two devices it finds are Grevill and Real Time Sequencer, no CoreMIDI4j devices

I "installed" the library by simply putting it in my Processing/libraries folder which I think is working, otherwise I would be getting errors on the imports. I'm stumped on how the library must be installed ok enough to not throw errors, working enough to return true on if it loaded properly, but still finds no other devices. Any thoughts?

If it helps, here's the file that's causing the issue https://github.com/vlucenaBigSweetOwl/TunePad/blob/master/MenuBar.pde

**Comment by brunchboy** [comment]
If the library reports that it is loaded, then it is installed and loaded properly.

I don’t understand what you mean by not finding CoreMidi4J devices though. What devices are you expecting to find? We don’t add additional devices compared to what the normal Java MIDI SPI shows, but we offer different versions of those devices: our versions properly support SysEx, and allow you to connect and remove MIDI devices to your system while your program is running.

**Comment by brunchboy** [comment]
Also, that link doesn’t seem to be valid, I get a 404 when I try to follow it.

**Comment by vlucenaBigSweetOwl** [comment]
Ah, then I think I'm just fundamentally not sure on how to go about doing what I want and CoreMIDI4J isn't what I'm looking for. Essentially, I'd like a Mac equivalent to Microsoft GS Wavetable Synth so I can send MIDI noteOn, noteOff signals and have them play out loud. I found myself here after daisy-chaining from the midibus processing library to mmj to here.

Also better link https://github.com/vlucenaBigSweetOwl/TunePad/blob/6f6d323c9fdaccdd0a6d8b879dc5c80e022c7890/MenuBar.pde

**Comment by brunchboy** [comment]
I have no idea what the Microsoft GS Wavetable Synth is, but Java has its own built-in synthesizers which you should be able to use in that manner? The Java MIDI API certainly implies that. I haven’t tried to use them, though; I use MIDI to communicate with hardware devices. But if you are not doing that, then you are probably right, CoreMidi4J is not necessary or helpful for you.

**Comment by brunchboy** [comment]
You can also certainly install a software synth on the Mac that supports MIDI, and use inter-application communication to control it from Java; I do that with Ableton Live sometimes. (And for whatever reason, that second link also results in a 404 for me.)

**Comment by vlucenaBigSweetOwl** [comment]
Thank you so much for the swift responses! I think you've given me a good heading of where to search next.
