### ISSUE TITLE
Timestamps appear to be random

### ISSUE THREAD

**Issue by brunchboy** [DerekCook/CoreMidi4J#5]
I don’t think timestamps are working; as I watch multiple messages come in, they jump around between huge negative and positive values. Perhaps they are being passed from the native code to Java using the wrong data size, or something? I think if we can’t track that down we should just go back to using -1 meaning we don’t know/care the value.

**Comment by DerekCook** [comment]
Yes, that was the problem (data size), although I only saw negative values in Java. The Core MIDItimestamp is a UINT32 and I mistakenly passed it in an INT value. I have changed the code in the branch we are currently testing to pass it as a long value. I had some debug code to monitor the timestamp in the native and java side and confirmed that they are now identical.
